# g5.12xlarge / g6.12xlarge Spot Availability — '둘 다 0이 아닌' 경우 + 지속 구간

`2026-03-13` ~ `2026-03-18` 데이터에서 두 인스턴스의 spot availability를 비교/필터링합니다.

**데이터/정의 (다른 노트북 기준)**
- 데이터: 같은 폴더의 `2026-03-*.csv` (`gpu_spot_analysis_o.ipynb`, `scenario_ranking_*.ipynb` 와 동일)
- 컬럼: `InstanceType, AZ, DDDRequestTime, Total(=5), Success, Fail, RequestDateTime`
- `g5.12xlarge` / `g6.12xlarge` 는 둘 다 `us-west-2c` AZ만 존재하고 `Success` 는 0~5
- **spot availability = instance 수 = `Success`** (가용 spot instance 개수, 0~5). GPU 환산(`×4`) 아님.
- 타임스탬프 정렬: `scenario_ranking_*.ipynb` 와 동일하게 **5분 resample + ffill**

**참고:** `g5=1 & g6=1` 동시 발생은 데이터상 **0회**. 둘 다 같은 값(g5==g6>0)으로 나타나는 값은 `3`, `5` 뿐.

In [1]:
import pandas as pd
import glob, os

# ============== 설정 ==============
START_DATE = '2026-03-13'
END_DATE   = '2026-03-18'   # inclusive

TARGETS  = ['g5.12xlarge', 'g6.12xlarge']
RESAMPLE = '5min'          # scenario_ranking_*.ipynb 와 동일
# availability = Success (instance 수, 0~5). GPU 환산 안 함.
# ==================================

In [2]:
# ----- CSV 로드 (날짜 범위 필터) -----
start = pd.Timestamp(START_DATE)
end   = pd.Timestamp(END_DATE)

all_csvs = sorted(glob.glob('./2026-*.csv'))
csv_files = [f for f in all_csvs
             if start <= pd.Timestamp(os.path.basename(f).replace('.csv', '')) <= end]
print('Loading:', [os.path.basename(f) for f in csv_files])

df_raw = pd.concat([pd.read_csv(f) for f in csv_files], ignore_index=True)
df_raw = df_raw[df_raw['InstanceType'].isin(TARGETS)].copy()
df_raw['RequestDateTime'] = pd.to_datetime(df_raw['RequestDateTime'])
df_raw = df_raw.sort_values('RequestDateTime').reset_index(drop=True)
print('rows per type:')
print(df_raw['InstanceType'].value_counts())

Loading: ['2026-03-13.csv', '2026-03-14.csv', '2026-03-15.csv', '2026-03-16.csv', '2026-03-17.csv', '2026-03-18.csv']
rows per type:
InstanceType
g5.12xlarge    855
g6.12xlarge    855
Name: count, dtype: int64

In [3]:
# ----- 인스턴스별 5분 resample + ffill, instance 수(Success) 결합 -----
cols = {}
for itype in TARGETS:
    sub = df_raw[df_raw['InstanceType'] == itype][['RequestDateTime', 'Success']].copy()
    sub = sub.set_index('RequestDateTime').sort_index()
    sub = sub[~sub.index.duplicated(keep='last')]
    sub.index = sub.index.floor(RESAMPLE)
    sub = sub[~sub.index.duplicated(keep='last')]
    sub = sub.resample(RESAMPLE).ffill()
    key = itype.split('.')[0]                 # 'g5' / 'g6'
    cols[f'{key}_avail'] = sub['Success']     # instance 수 (0~5)

avail = pd.DataFrame(cols).dropna().astype(int)
avail['sum_avail'] = avail['g5_avail'] + avail['g6_avail']
avail.index.name = 'time'
print(f'결합 후 timeline: {avail.index.min()} ~ {avail.index.max()}  ({len(avail)} points)')
avail.head()

결합 후 timeline: 2026-03-13 01:20:00 ~ 2026-03-18 23:50:00  (1711 points)

                     g5_avail  g6_avail  sum_avail
time
2026-03-13 01:20:00         0         5          5
2026-03-13 01:25:00         0         5          5
2026-03-13 01:30:00         0         5          5
2026-03-13 01:35:00         0         5          5
2026-03-13 01:40:00         0         5          5

## 필터: 둘 다 0이 아닌 경우 (`g5 > 0` and `g6 > 0`)

In [4]:
both_nonzero = (avail['g5_avail'] > 0) & (avail['g6_avail'] > 0)
f = avail[both_nonzero].copy()
print(f'둘 다 0이 아닌 경우: {len(f)} / {len(avail)} points')
with pd.option_context('display.max_rows', None):
    display(f.reset_index())

둘 다 0이 아닌 경우: 356 / 1711 points

                   time  g5_avail  g6_avail  sum_avail
0   2026-03-15 06:00:00         2         5          7
1   2026-03-15 06:05:00         2         5          7
2   2026-03-15 06:10:00         1         5          6
3   2026-03-15 06:15:00         1         5          6
4   2026-03-15 07:30:00         4         5          9
5   2026-03-15 07:35:00         4         5          9
6   2026-03-15 08:00:00         2         5          7
7   2026-03-15 08:05:00         2         5          7
8   2026-03-15 08:10:00         3         5          8
9   2026-03-15 08:15:00         3         5          8
10  2026-03-15 08:20:00         5         5         10
11  2026-03-15 08:25:00         5         5         10
12  2026-03-15 08:30:00         5         5         10
13  2026-03-15 08:35:00         5         5         10
14  2026-03-15 08:40:00         5         5         10
15  2026-03-15 08:45:00         5         5         10
16  2026-03-15 08:50:00         5         5         10
17  2026-03-15 08:55:00         5         5         10
18  2026-03-15 09:00:00         5         5         10
19  2026-03-15 09:05:00         5         5         10
20  2026-03-15 09:10:00         3         5          8
21  2026-03-15 09:15:00         3         5          8
22  2026-03-15 09:20:00         5         5         10
23  2026-03-15 09:25:00         5         5         10
24  2026-03-15 09:30:00         5         5         10
25  2026-03-15 09:35:00         5         5         10
26  2026-03-15 09:40:00         5         5         10
27  2026-03-15 09:45:00         5         5         10
28  2026-03-15 09:50:00         5         5         10
29  2026-03-15 09:55:00         5         5         10
30  2026-03-15 10:00:00         5         5         10
31  2026-03-15 10:05:00         5         5         10
32  2026-03-15 10:10:00         5         5         10
33  2026-03-15 10:15:00         5         5         10
34  2026-03-15 10:20:00         3         5          8
35  2026-03-15 10:25:00         3         5          8
36  2026-03-15 10:40:00         2         5          7
37  2026-03-15 10:45:00         2         5          7
38  2026-03-15 11:00:00         2         5          7
39  2026-03-15 11:05:00         2         5          7
40  2026-03-15 11:10:00         1         5          6
41  2026-03-15 11:15:00         1         5          6
42  2026-03-15 11:20:00         1         5          6
43  2026-03-15 11:25:00         1         5          6
44  2026-03-15 11:30:00         2         5          7
45  2026-03-15 11:35:00         2         5          7
46  2026-03-15 11:40:00         3         5          8
47  2026-03-15 11:45:00         3         5          8
48  2026-03-15 11:50:00         1         5          6
49  2026-03-15 11:55:00         1         5          6
50  2026-03-15 12:00:00         5         5         10
51  2026-03-15 12:05:00         5         5         10
52  2026-03-15 12:10:00         5         5         10
53  2026-03-15 12:15:00         5         5         10
54  2026-03-15 12:20:00         5         5         10
55  2026-03-15 12:25:00         5         5         10
56  2026-03-15 12:30:00         5         5         10
57  2026-03-15 12:35:00         5         5         10
58  2026-03-15 12:40:00         2         5          7
59  2026-03-15 12:45:00         2         5          7
60  2026-03-15 12:50:00         5         5         10
61  2026-03-15 12:55:00         5         5         10
62  2026-03-15 13:00:00         5         5         10
63  2026-03-15 13:05:00         5         5         10
64  2026-03-15 13:10:00         3         5          8
65  2026-03-15 13:15:00         3         5          8
66  2026-03-15 13:20:00         4         5          9
67  2026-03-15 13:25:00         4         5          9
68  2026-03-15 13:30:00         4         5          9
69  2026-03-15 13:35:00         4         5          9
70  2026-03-15 13:40:00         4         5          9
71  2026-03-15 13:45:00         4         5          9
72  2026-03-15 13:50:00         5         5         10
73  2026-03-15 13:55:00         5         5         10
74  2026-03-15 14:00:00         2         5          7
75  2026-03-15 14:05:00         2         5          7
76  2026-03-15 14:10:00         5         5         10
77  2026-03-15 14:15:00         5         5         10
78  2026-03-15 14:20:00         5         5         10
79  2026-03-15 14:25:00         5         5         10
80  2026-03-15 15:20:00         1         5          6
81  2026-03-15 15:25:00         1         5          6
82  2026-03-15 15:30:00         4         5          9
83  2026-03-15 15:35:00         4         5          9
84  2026-03-15 15:40:00         5         5         10
85  2026-03-15 15:45:00         5         5         10
86  2026-03-15 15:50:00         5         4          9
87  2026-03-15 15:55:00         5         4          9
88  2026-03-15 16:00:00         5         5         10
89  2026-03-15 16:05:00         5         5         10
90  2026-03-15 16:10:00         2         5          7
91  2026-03-15 16:15:00         2         5          7
92  2026-03-15 16:20:00         3         5          8
93  2026-03-15 16:25:00         3         5          8
94  2026-03-15 16:30:00         5         5         10
95  2026-03-15 16:35:00         5         5         10
96  2026-03-15 16:40:00         5         5         10
97  2026-03-15 16:45:00         5         5         10
98  2026-03-15 16:50:00         3         5          8
99  2026-03-15 16:55:00         3         5          8
100 2026-03-15 17:10:00         1         5          6
101 2026-03-15 17:15:00         1         5          6
102 2026-03-15 17:20:00         5         5         10
103 2026-03-15 17:25:00         5         5         10
104 2026-03-15 17:30:00         4         5          9
105 2026-03-15 17:35:00         4         5          9
106 2026-03-15 17:40:00         5         5         10
107 2026-03-15 17:45:00         5         5         10
108 2026-03-15 18:00:00         5         5         10
109 2026-03-15 18:05:00         5         5         10
110 2026-03-15 18:10:00         4         5          9
111 2026-03-15 18:15:00         4         5          9
112 2026-03-15 18:30:00         5         5         10
113 2026-03-15 18:35:00         5         5         10
114 2026-03-15 18:40:00         4         5          9
115 2026-03-15 18:45:00         4         5          9
116 2026-03-15 18:50:00         1         5          6
117 2026-03-15 18:55:00         1         5          6
118 2026-03-15 19:00:00         4         5          9
119 2026-03-15 19:05:00         4         5          9
120 2026-03-15 19:20:00         5         5         10
121 2026-03-15 19:25:00         5         5         10
122 2026-03-15 19:30:00         5         5         10
123 2026-03-15 19:35:00         5         5         10
124 2026-03-15 19:40:00         5         5         10
125 2026-03-15 19:45:00         5         5         10
126 2026-03-15 19:50:00         2         5          7
127 2026-03-15 19:55:00         2         5          7
128 2026-03-15 20:00:00         4         5          9
129 2026-03-15 20:05:00         4         5          9
130 2026-03-15 20:10:00         4         5          9
131 2026-03-15 20:15:00         4         5          9
132 2026-03-15 20:40:00         5         5         10
133 2026-03-15 20:45:00         5         5         10
134 2026-03-15 20:50:00         5         5         10
135 2026-03-15 20:55:00         5         5         10
136 2026-03-15 21:00:00         5         5         10
137 2026-03-15 21:05:00         5         5         10
138 2026-03-15 21:10:00         5         5         10
139 2026-03-15 21:15:00         5         5         10
140 2026-03-15 21:20:00         4         5          9
141 2026-03-15 21:25:00         4         5          9
142 2026-03-15 21:30:00         5         5         10
143 2026-03-15 21:35:00         5         5         10
144 2026-03-15 21:40:00         5         5         10
145 2026-03-15 21:45:00         5         5         10
146 2026-03-15 21:50:00         1         5          6
147 2026-03-15 21:55:00         1         5          6
148 2026-03-15 22:00:00         3         5          8
149 2026-03-15 22:05:00         3         5          8
150 2026-03-15 22:10:00         2         5          7
151 2026-03-15 22:15:00         2         5          7
152 2026-03-15 22:20:00         5         5         10
153 2026-03-15 22:25:00         5         5         10
154 2026-03-15 22:40:00         4         5          9
155 2026-03-15 22:45:00         4         5          9
156 2026-03-15 22:50:00         5         5         10
157 2026-03-15 22:55:00         5         5         10
158 2026-03-15 23:00:00         5         5         10
159 2026-03-15 23:05:00         5         5         10
160 2026-03-15 23:10:00         5         5         10
161 2026-03-15 23:15:00         5         5         10
162 2026-03-15 23:20:00         5         5         10
163 2026-03-15 23:25:00         5         5         10
164 2026-03-15 23:30:00         5         5         10
165 2026-03-15 23:35:00         5         5         10
166 2026-03-15 23:40:00         5         5         10
167 2026-03-15 23:45:00         5         5         10
168 2026-03-15 23:50:00         5         5         10
169 2026-03-15 23:55:00         5         5         10
170 2026-03-16 00:00:00         5         5         10
171 2026-03-16 00:05:00         5         5         10
172 2026-03-16 00:20:00         5         3          8
173 2026-03-16 00:25:00         5         3          8
174 2026-03-16 00:30:00         5         4          9
175 2026-03-16 00:35:00         5         4          9
176 2026-03-16 00:40:00         5         5         10
177 2026-03-16 00:45:00         5         5         10
178 2026-03-16 00:50:00         5         5         10
179 2026-03-16 00:55:00         5         5         10
180 2026-03-16 01:00:00         5         5         10
181 2026-03-16 01:05:00         5         5         10
182 2026-03-16 01:10:00         5         5         10
183 2026-03-16 01:15:00         5         5         10
184 2026-03-16 01:20:00         3         3          6
185 2026-03-16 01:25:00         3         3          6
186 2026-03-16 01:30:00         3         5          8
187 2026-03-16 01:35:00         3         5          8
188 2026-03-16 01:40:00         3         5          8
189 2026-03-16 01:45:00         3         5          8
190 2026-03-16 01:50:00         5         5         10
191 2026-03-16 01:55:00         5         5         10
192 2026-03-16 02:00:00         5         5         10
193 2026-03-16 02:05:00         5         5         10
194 2026-03-16 02:10:00         4         5          9
195 2026-03-16 02:15:00         4         5          9
196 2026-03-16 02:20:00         2         5          7
197 2026-03-16 02:25:00         2         5          7
198 2026-03-16 02:30:00         5         5         10
199 2026-03-16 02:35:00         5         5         10
200 2026-03-16 02:40:00         4         5          9
201 2026-03-16 02:45:00         4         5          9
202 2026-03-16 02:50:00         5         5         10
203 2026-03-16 02:55:00         5         5         10
204 2026-03-16 03:00:00         5         5         10
205 2026-03-16 03:05:00         5         5         10
206 2026-03-16 03:20:00         1         3          4
207 2026-03-16 03:25:00         1         3          4
208 2026-03-16 04:40:00         2         5          7
209 2026-03-16 04:45:00         2         5          7
210 2026-03-16 05:50:00         5         5         10
211 2026-03-16 05:55:00         5         5         10
212 2026-03-16 06:00:00         5         5         10
213 2026-03-16 06:05:00         5         5         10
214 2026-03-16 06:30:00         1         5          6
215 2026-03-16 06:35:00         1         5          6
216 2026-03-16 07:50:00         1         5          6
217 2026-03-16 07:55:00         1         5          6
218 2026-03-16 08:00:00         5         5         10
219 2026-03-16 08:05:00         5         5         10
220 2026-03-16 08:10:00         4         5          9
221 2026-03-16 08:15:00         4         5          9
222 2026-03-16 08:20:00         1         5          6
223 2026-03-16 08:25:00         1         5          6
224 2026-03-16 08:30:00         1         5          6
225 2026-03-16 08:35:00         1         5          6
226 2026-03-16 08:40:00         4         5          9
227 2026-03-16 08:45:00         4         5          9
228 2026-03-16 09:00:00         2         5          7
229 2026-03-16 09:05:00         2         5          7
230 2026-03-16 09:10:00         3         5          8
231 2026-03-16 09:15:00         3         5          8
232 2026-03-16 10:00:00         1         5          6
233 2026-03-16 10:05:00         1         5          6
234 2026-03-16 10:10:00         2         5          7
235 2026-03-16 10:15:00         2         5          7
236 2026-03-16 10:40:00         1         5          6
237 2026-03-16 10:45:00         1         5          6
238 2026-03-17 07:50:00         3         5          8
239 2026-03-17 07:55:00         3         5          8
240 2026-03-17 08:10:00         5         1          6
241 2026-03-17 08:15:00         5         1          6
242 2026-03-17 08:20:00         2         5          7
243 2026-03-17 08:25:00         2         5          7
244 2026-03-17 08:30:00         5         5         10
245 2026-03-17 08:35:00         5         5         10
246 2026-03-17 08:40:00         5         5         10
247 2026-03-17 08:45:00         5         5         10
248 2026-03-17 08:50:00         5         5         10
249 2026-03-17 08:55:00         5         5         10
250 2026-03-17 09:00:00         5         5         10
251 2026-03-17 09:05:00         5         5         10
252 2026-03-17 09:10:00         5         5         10
253 2026-03-17 09:15:00         5         5         10
254 2026-03-17 09:20:00         5         5         10
255 2026-03-17 09:25:00         5         5         10
256 2026-03-17 09:30:00         5         5         10
257 2026-03-17 09:35:00         5         5         10
258 2026-03-17 09:40:00         5         4          9
259 2026-03-17 09:45:00         5         4          9
260 2026-03-17 09:50:00         1         5          6
261 2026-03-17 09:55:00         1         5          6
262 2026-03-17 11:10:00         1         5          6
263 2026-03-17 11:15:00         1         5          6
264 2026-03-17 11:20:00         3         5          8
265 2026-03-17 11:25:00         3         5          8
266 2026-03-17 14:30:00         1         5          6
267 2026-03-17 14:35:00         1         5          6
268 2026-03-17 14:40:00         5         5         10
269 2026-03-17 14:45:00         5         5         10
270 2026-03-17 14:50:00         5         5         10
271 2026-03-17 14:55:00         5         5         10
272 2026-03-17 15:00:00         4         5          9
273 2026-03-17 15:05:00         4         5          9
274 2026-03-17 15:10:00         3         5          8
275 2026-03-17 15:15:00         3         5          8
276 2026-03-17 15:20:00         5         2          7
277 2026-03-17 15:25:00         5         2          7
278 2026-03-17 15:30:00         5         5         10
279 2026-03-17 15:35:00         5         5         10
280 2026-03-17 15:40:00         5         5         10
281 2026-03-17 15:45:00         5         5         10
282 2026-03-17 15:50:00         5         1          6
283 2026-03-17 15:55:00         5         1          6
284 2026-03-17 18:20:00         2         5          7
285 2026-03-17 18:25:00         2         5          7
286 2026-03-17 18:30:00         5         5         10
287 2026-03-17 18:35:00         5         5         10
288 2026-03-17 19:00:00         1         5          6
289 2026-03-17 19:05:00         1         5          6
290 2026-03-17 19:20:00         5         1          6
291 2026-03-17 19:25:00         5         1          6
292 2026-03-17 19:30:00         5         1          6
293 2026-03-17 19:35:00         5         1          6
294 2026-03-17 19:50:00         4         2          6
295 2026-03-17 19:55:00         4         2          6
296 2026-03-17 20:00:00         3         5          8
297 2026-03-17 20:05:00         3         5          8
298 2026-03-17 20:10:00         5         2          7
299 2026-03-17 20:15:00         5         2          7
300 2026-03-18 02:20:00         5         2          7
301 2026-03-18 02:25:00         5         2          7
302 2026-03-18 02:40:00         2         4          6
303 2026-03-18 02:45:00         2         4          6
304 2026-03-18 02:50:00         1         3          4
305 2026-03-18 02:55:00         1         3          4
306 2026-03-18 03:00:00         5         4          9
307 2026-03-18 03:05:00         5         4          9
308 2026-03-18 03:10:00         3         3          6
309 2026-03-18 03:15:00         3         3          6
310 2026-03-18 03:20:00         3         4          7
311 2026-03-18 03:25:00         3         4          7
312 2026-03-18 03:40:00         5         4          9
313 2026-03-18 03:45:00         5         4          9
314 2026-03-18 03:50:00         5         5         10
315 2026-03-18 03:55:00         5         5         10
316 2026-03-18 04:40:00         5         5         10
317 2026-03-18 04:45:00         5         5         10
318 2026-03-18 05:20:00         2         5          7
319 2026-03-18 05:25:00         2         5          7
320 2026-03-18 05:30:00         1         5          6
321 2026-03-18 05:35:00         1         5          6
322 2026-03-18 06:50:00         5         2          7
323 2026-03-18 06:55:00         5         2          7
324 2026-03-18 07:20:00         2         1          3
325 2026-03-18 07:25:00         2         1          3
326 2026-03-18 07:30:00         5         2          7
327 2026-03-18 07:35:00         5         2          7
328 2026-03-18 07:50:00         5         1          6
329 2026-03-18 07:55:00         5         1          6
330 2026-03-18 12:20:00         5         5         10
331 2026-03-18 12:25:00         5         5         10
332 2026-03-18 12:30:00         2         5          7
333 2026-03-18 12:35:00         2         5          7
334 2026-03-18 12:40:00         1         5          6
335 2026-03-18 12:45:00         1         5          6
336 2026-03-18 13:20:00         5         5         10
337 2026-03-18 13:25:00         5         5         10
338 2026-03-18 13:30:00         3         5          8
339 2026-03-18 13:35:00         3         5          8
340 2026-03-18 14:30:00         3         5          8
341 2026-03-18 14:35:00         3         5          8
342 2026-03-18 14:40:00         4         5          9
343 2026-03-18 14:45:00         4         5          9
344 2026-03-18 15:20:00         5         5         10
345 2026-03-18 15:25:00         5         5         10
346 2026-03-18 15:30:00         5         5         10
347 2026-03-18 15:35:00         5         5         10
348 2026-03-18 15:40:00         5         5         10
349 2026-03-18 15:45:00         5         5         10
350 2026-03-18 16:30:00         5         1          6
351 2026-03-18 16:35:00         5         1          6
352 2026-03-18 16:40:00         3         1          4
353 2026-03-18 16:45:00         3         1          4
354 2026-03-18 16:50:00         2         1          3
355 2026-03-18 16:55:00         2         1          3

## (참고) (g5_avail, g6_avail) 조합별 개수

In [5]:
print(f.groupby(['g5_avail', 'g6_avail']).size().rename('count'))

g5_avail  g6_avail
1         3             4
          5            40
2         1             4
          4             2
          5            36
3         1             2
          3             4
          4             2
          5            34
4         2             2
          5            38
5         1            12
          2            10
          3             2
          4            10
          5           154
Name: count, dtype: int64

## 연속 지속 구간 (run-length) 분석

어떤 조건(mask)이 5분 그리드에서 **연속으로(중간에 끊김 없이)** 얼마나 오래 유지됐는지 계산합니다.
- `N개 슬롯` = `N × 5분` 커버 구간
- 표시 구간 `start ~ end` 는 각 슬롯 시작 시각 기준

In [6]:
STEP = pd.Timedelta(RESAMPLE)

def all_runs(mask):
    """연속(5분 간격) True 구간 목록 -> [(start, end, n_slots), ...]"""
    idx = mask.index
    runs = []
    s = prev = None
    n = 0
    for t, v in zip(idx, mask.values):
        if v:
            if s is None or (t - prev) != STEP:
                if s is not None:
                    runs.append((s, prev, n))
                s = t
                n = 1
            else:
                n += 1
            prev = t
        else:
            if s is not None:
                runs.append((s, prev, n))
                s = None
    if s is not None:
        runs.append((s, prev, n))
    return runs

def summarize(name, mask):
    runs = all_runs(mask)
    cnt = int(mask.sum())
    if not runs:
        print(f'[{name}] 발생 0회 -> 지속 구간 없음')
        return None
    s, e, n = max(runs, key=lambda r: r[2])
    print(f'[{name}] 총 {cnt} slots, 구간 {len(runs)}개, '
          f'최장 = {n} slots ({n*5}분)  {s} ~ {e} (+5분 ={e+STEP})')
    return (s, e, n)

In [7]:
g5a, g6a = avail['g5_avail'], avail['g6_avail']

# 1) 문자 그대로 둘 다 1 인 경우
summarize('g5==1 & g6==1', (g5a == 1) & (g6a == 1))

# 2) 1:1 동률 (g5 == g6, 둘 다 >0)
summarize('balanced g5==g6 (>0)', (g5a == g6a) & (g5a > 0))

# 3) 둘 다 0이 아닌 경우
summarize('both nonzero', (g5a > 0) & (g6a > 0))

[g5==1 & g6==1] 발생 0회 -> 지속 구간 없음
[balanced g5==g6 (>0)] 총 158 slots, 구간 34개, 최장 = 16 slots (80분)  2026-03-15 22:50:00 ~ 2026-03-16 00:05:00 (+5분 =2026-03-16 00:10:00)
[both nonzero] 총 356 slots, 구간 42개, 최장 = 42 slots (210분)  2026-03-15 11:00:00 ~ 2026-03-15 14:25:00 (+5분 =2026-03-15 14:30:00)

(Timestamp('2026-03-15 11:00:00'), Timestamp('2026-03-15 14:25:00'), 42)

### 1:1 동률(g5==g6>0) 구간 전체 (긴 순서)

In [8]:
runs = all_runs((g5a == g6a) & (g5a > 0))
runs_df = pd.DataFrame(
    [(s, e, n, n * 5, int(avail.loc[s, 'g5_avail'])) for s, e, n in runs],
    columns=['start', 'end', 'n_slots', 'minutes', 'value(g5=g6)'],
).sort_values('n_slots', ascending=False).reset_index(drop=True)
runs_df

                 start                 end  n_slots  minutes  value(g5=g6)
0  2026-03-15 22:50:00 2026-03-16 00:05:00       16       80             5
1  2026-03-17 08:30:00 2026-03-17 09:35:00       14       70             5
2  2026-03-15 09:20:00 2026-03-15 10:15:00       12       60             5
3  2026-03-16 00:40:00 2026-03-16 01:25:00       10       50             5
4  2026-03-15 08:20:00 2026-03-15 09:05:00       10       50             5
5  2026-03-15 12:00:00 2026-03-15 12:35:00        8       40             5
6  2026-03-15 20:40:00 2026-03-15 21:15:00        8       40             5
7  2026-03-18 15:20:00 2026-03-18 15:45:00        6       30             5
8  2026-03-15 19:20:00 2026-03-15 19:45:00        6       30             5
9  2026-03-15 21:30:00 2026-03-15 21:45:00        4       20             5
10 2026-03-17 15:30:00 2026-03-17 15:45:00        4       20             5
11 2026-03-17 14:40:00 2026-03-17 14:55:00        4       20             5
12 2026-03-16 05:50:00 2026-03-16 06:05:00        4       20             5
13 2026-03-16 02:50:00 2026-03-16 03:05:00        4       20             5
14 2026-03-15 12:50:00 2026-03-15 13:05:00        4       20             5
15 2026-03-15 14:10:00 2026-03-15 14:25:00        4       20             5
16 2026-03-15 16:30:00 2026-03-15 16:45:00        4       20             5
17 2026-03-16 01:50:00 2026-03-16 02:05:00        4       20             5
18 2026-03-15 18:30:00 2026-03-15 18:35:00        2       10             5
19 2026-03-15 15:40:00 2026-03-15 15:45:00        2       10             5
20 2026-03-16 02:30:00 2026-03-16 02:35:00        2       10             5
21 2026-03-15 18:00:00 2026-03-15 18:05:00        2       10             5
22 2026-03-15 17:40:00 2026-03-15 17:45:00        2       10             5
23 2026-03-16 08:00:00 2026-03-16 08:05:00        2       10             5
24 2026-03-15 17:20:00 2026-03-15 17:25:00        2       10             5
25 2026-03-15 13:50:00 2026-03-15 13:55:00        2       10             5
26 2026-03-15 16:00:00 2026-03-15 16:05:00        2       10             5
27 2026-03-17 18:30:00 2026-03-17 18:35:00        2       10             5
28 2026-03-18 03:10:00 2026-03-18 03:15:00        2       10             3
29 2026-03-18 03:50:00 2026-03-18 03:55:00        2       10             5
30 2026-03-18 04:40:00 2026-03-18 04:45:00        2       10             5
31 2026-03-18 12:20:00 2026-03-18 12:25:00        2       10             5
32 2026-03-18 13:20:00 2026-03-18 13:25:00        2       10             5
33 2026-03-15 22:20:00 2026-03-15 22:25:00        2       10             5