# KV Cache Migration vs Re-computing — 정량 분석

figure 가 아니라 **수치 분석**용 노트북. 두 방식의 시간 차이를 context length / model / instance 별로 비교한다.

**데이터** (`figures/plot_comparison.py` 와 동일한 매칭 규칙)
- `kv_cache_migration.csv` : `Context Length, Model Size, Source/Destination Instance, KV Cache Size (MiB), KV Cache Transfer Time (ms), Network Bandwidth (GB/s)`
- `recomputing.csv` : `Context Length, Model Size, Instance Type, Re-Computing Latency (ms)`

**비교의 의미 (migration 의사결정)**
- 요청을 instance A→B 로 옮길 때: ① B 에서 KV 재계산(recompute) vs ② A 에서 B 로 KV 전송(migration).
- 따라서 **recompute 는 항상 destination instance 기준** 으로 매칭한다.
- instance 매핑: `L4 (g6.xlarge)` ↔ `g6.xlarge`, `L40S (g6e.xlarge)` ↔ `g6e.xlarge`.
- **70B 매핑**: KV migration 의 `70B` 는 *해당 instance 에 올라가는 layer 수만큼의 KV* 다 (g6.xlarge=2 layer, g6e.xlarge=8 layer). recompute 의 `70B(2layer)`/`70B(8layer)` 와 layer 수가 이미 일치하므로 **정규화 없이 직접 비교**한다.
- recompute 가 `NaN` = 해당 instance 에서 그 context 가 OOM/측정불가 → **migration 이 사실상 유일한 선택**.

**부호 규약**: `diff_ms = migrate_ms - recompute_ms` (양수면 migration 이 더 느림), `ratio = migrate_ms / recompute_ms` (>1 이면 recompute 가 빠름).

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 200)
pd.set_option('display.width', 160)
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

kv = pd.read_csv('kv_cache_migration.csv')
rc = pd.read_csv('recomputing.csv')

# --- recompute 쪽 정리: instance 약칭 + 70B layer 라벨 통합 ---
INST = {'L4 (g6.xlarge)': 'g6.xlarge', 'L40S (g6e.xlarge)': 'g6e.xlarge'}
rc['dst'] = rc['Instance Type'].map(INST)
rc['model'] = rc['Model Size'].apply(lambda m: '70B' if m.startswith('70B') else m)
rc2 = rc.rename(columns={'Context Length': 'ctx',
                         'Re-Computing Latency (ms)': 'recompute_ms'})[['model', 'dst', 'ctx', 'recompute_ms']]

# --- migration 쪽 정리 ---
kv2 = kv.rename(columns={'Model Size': 'model', 'Source Instance': 'src',
                         'Destination Instance': 'dst', 'Context Length': 'ctx',
                         'KV Cache Transfer Time (ms)': 'migrate_ms',
                         'KV Cache Size (MiB)': 'kv_MiB',
                         'Network Bandwidth (GB/s)': 'bw'})

# --- recompute(=destination 기준) 와 merge ---
df = kv2.merge(rc2, on=['model', 'dst', 'ctx'], how='left')
df['pair'] = df['src'] + '->' + df['dst']

# --- 핵심 지표 ---
df['diff_ms'] = df['migrate_ms'] - df['recompute_ms']
df['ratio']   = df['migrate_ms'] / df['recompute_ms']
df['faster']  = np.where(df['recompute_ms'].isna(), 'migration (recompute OOM)',
                np.where(df['migrate_ms'] < df['recompute_ms'], 'migration', 'recompute'))
df['kv_GB']   = df['kv_MiB'] / 1024
# migration 이 recompute 와 같아지려면 필요한 대역폭 (= bw_actual * ratio)
df['breakeven_bw_GBps'] = df['kv_GB'] / (df['recompute_ms'] / 1000)

df = df.sort_values(['model', 'pair', 'ctx']).reset_index(drop=True)
print(f'merged rows: {len(df)}  (recompute 있음 {df.recompute_ms.notna().sum()}, OOM {df.recompute_ms.isna().sum()})')
print('models:', sorted(df.model.unique()), '| pairs:', sorted(df.pair.unique()))
df.head()

merged rows: 100  (recompute 있음 95, OOM 5)
models: ['3B', '70B', '8B'] | pairs: ['g6.xlarge->g6.xlarge', 'g6.xlarge->g6e.xlarge', 'g6e.xlarge->g6.xlarge', 'g6e.xlarge->g6e.xlarge']

    ctx model        src        dst  kv_MiB  migrate_ms   bw  recompute_ms                  pair  diff_ms  ratio     faster  kv_GB  breakeven_bw_GBps
0   128    3B  g6.xlarge  g6.xlarge      14       44.98 0.30         37.80  g6.xlarge->g6.xlarge     7.18   1.19  recompute   0.01               0.36
1   256    3B  g6.xlarge  g6.xlarge      28       94.23 0.29         38.00  g6.xlarge->g6.xlarge    56.23   2.48  recompute   0.03               0.72
2   512    3B  g6.xlarge  g6.xlarge      56      188.91 0.29         45.90  g6.xlarge->g6.xlarge   143.01   4.12  recompute   0.05               1.19
3  1024    3B  g6.xlarge  g6.xlarge     112      378.34 0.29         70.00  g6.xlarge->g6.xlarge   308.34   5.40  recompute   0.11               1.56
4  2048    3B  g6.xlarge  g6.xlarge     224      757.22 0.29        121.70  g6.xlarge->g6.xlarge   635.52   6.22  recompute   0.22               1.80

## 1. 전체 비교 테이블
config(model, pair) × context 별 migration/recompute 시간, 차이, 비율, 승자.

In [2]:
view = df[['model', 'pair', 'ctx', 'kv_MiB', 'migrate_ms', 'recompute_ms',
           'diff_ms', 'ratio', 'faster']]
with pd.option_context('display.max_rows', None):
    display(view)

   model                    pair    ctx  kv_MiB  migrate_ms  recompute_ms   diff_ms  ratio                     faster
0     3B    g6.xlarge->g6.xlarge    128      14       44.98         37.80      7.18   1.19                  recompute
1     3B    g6.xlarge->g6.xlarge    256      28       94.23         38.00     56.23   2.48                  recompute
2     3B    g6.xlarge->g6.xlarge    512      56      188.91         45.90    143.01   4.12                  recompute
3     3B    g6.xlarge->g6.xlarge   1024     112      378.34         70.00    308.34   5.40                  recompute
4     3B    g6.xlarge->g6.xlarge   2048     224      757.22        121.70    635.52   6.22                  recompute
5     3B    g6.xlarge->g6.xlarge   4096     448    1,513.77        253.20  1,260.57   5.98                  recompute
6     3B    g6.xlarge->g6.xlarge   8192     896    3,028.26        574.60  2,453.66   5.27                  recompute
7     3B    g6.xlarge->g6.xlarge  16384    1792    6,057.26      2,312.20  3,745.06   2.62                  recompute
8     3B    g6.xlarge->g6.xlarge  32768    3584   12,122.50      6,382.20  5,740.30   1.90                  recompute
9     3B    g6.xlarge->g6.xlarge  65536    7168   24,231.85     20,002.80  4,229.05   1.21                  recompute
10    3B   g6.xlarge->g6e.xlarge    128      14       46.39         20.40     25.99   2.27                  recompute
11    3B   g6.xlarge->g6e.xlarge    256      28       94.48         19.43     75.05   4.86                  recompute
12    3B   g6.xlarge->g6e.xlarge    512      56      189.62         21.02    168.60   9.02                  recompute
13    3B   g6.xlarge->g6e.xlarge   1024     112      377.56         25.83    351.73  14.62                  recompute
14    3B   g6.xlarge->g6e.xlarge   2048     224      757.05         42.64    714.41  17.75                  recompute
15    3B   g6.xlarge->g6e.xlarge   4096     448    1,514.15         83.88  1,430.27  18.05                  recompute
16    3B   g6.xlarge->g6e.xlarge   8192     896    3,029.32        167.93  2,861.39  18.04                  recompute
17    3B   g6.xlarge->g6e.xlarge  16384    1792    6,057.58        420.83  5,636.75  14.39                  recompute
18    3B   g6.xlarge->g6e.xlarge  32768    3584   12,126.50      1,381.27 10,745.23   8.78                  recompute
19    3B   g6.xlarge->g6e.xlarge  65536    7168   24,244.74      5,867.33 18,377.41   4.13                  recompute
20    3B   g6e.xlarge->g6.xlarge    128      14       45.08         37.80      7.28   1.19                  recompute
21    3B   g6e.xlarge->g6.xlarge    256      28       94.19         38.00     56.19   2.48                  recompute
22    3B   g6e.xlarge->g6.xlarge    512      56      188.52         45.90    142.62   4.11                  recompute
23    3B   g6e.xlarge->g6.xlarge   1024     112      376.41         70.00    306.41   5.38                  recompute
24    3B   g6e.xlarge->g6.xlarge   2048     224      756.76        121.70    635.06   6.22                  recompute
25    3B   g6e.xlarge->g6.xlarge   4096     448    1,513.45        253.20  1,260.25   5.98                  recompute
26    3B   g6e.xlarge->g6.xlarge   8192     896    3,028.32        574.60  2,453.72   5.27                  recompute
27    3B   g6e.xlarge->g6.xlarge  16384    1792    6,057.56      2,312.20  3,745.36   2.62                  recompute
28    3B   g6e.xlarge->g6.xlarge  32768    3584   12,125.53      6,382.20  5,743.33   1.90                  recompute
29    3B   g6e.xlarge->g6.xlarge  65536    7168   24,232.69     20,002.80  4,229.89   1.21                  recompute
30    3B  g6e.xlarge->g6e.xlarge    128      14       49.51         20.40     29.11   2.43                  recompute
31    3B  g6e.xlarge->g6e.xlarge    256      28       92.86         19.43     73.43   4.78                  recompute
32    3B  g6e.xlarge->g6e.xlarge    512      56      187.39         21.02    166.37   8.91                  recompute
33    3B  g6e.xlarge->g6e.xlarge   1024     112      377.41         25.83    351.58  14.61                  recompute
34    3B  g6e.xlarge->g6e.xlarge   2048     224      757.25         42.64    714.61  17.76                  recompute
35    3B  g6e.xlarge->g6e.xlarge   4096     448    1,514.48         83.88  1,430.60  18.06                  recompute
36    3B  g6e.xlarge->g6e.xlarge   8192     896    3,028.52        167.93  2,860.59  18.03                  recompute
37    3B  g6e.xlarge->g6e.xlarge  16384    1792    6,057.23        420.83  5,636.40  14.39                  recompute
38    3B  g6e.xlarge->g6e.xlarge  32768    3584   12,116.95      1,381.27 10,735.68   8.77                  recompute
39    3B  g6e.xlarge->g6e.xlarge  65536    7168   24,233.17      5,867.33 18,365.84   4.13                  recompute
40   70B    g6.xlarge->g6.xlarge    128       1        0.64         30.60    -29.96   0.02                  migration
41   70B    g6.xlarge->g6.xlarge    256       2        4.44         30.30    -25.86   0.15                  migration
42   70B    g6.xlarge->g6.xlarge    512       4       11.14         33.30    -22.16   0.33                  migration
43   70B    g6.xlarge->g6.xlarge   1024       8       26.96         45.40    -18.44   0.59                  migration
44   70B    g6.xlarge->g6.xlarge   2048      16       54.04         75.50    -21.46   0.72                  migration
45   70B    g6.xlarge->g6.xlarge   4096      32      107.12        143.10    -35.98   0.75                  migration
46   70B    g6.xlarge->g6.xlarge   8192      64      216.35        283.40    -67.05   0.76                  migration
47   70B    g6.xlarge->g6.xlarge  16384     128      432.82        602.00   -169.18   0.72                  migration
48   70B    g6.xlarge->g6.xlarge  32768     256      863.81      1,415.60   -551.79   0.61                  migration
49   70B    g6.xlarge->g6.xlarge  65536     512    1,730.47           NaN       NaN    NaN  migration (recompute OOM)
50   70B  g6e.xlarge->g6e.xlarge    128       4        9.33         32.73    -23.40   0.29                  migration
51   70B  g6e.xlarge->g6e.xlarge    256       8       25.75         32.82     -7.07   0.78                  migration
52   70B  g6e.xlarge->g6e.xlarge    512      16       54.08         36.17     17.91   1.50                  recompute
53   70B  g6e.xlarge->g6e.xlarge   1024      32      108.48         45.62     62.86   2.38                  recompute
54   70B  g6e.xlarge->g6e.xlarge   2048      64      215.83         77.68    138.15   2.78                  recompute
55   70B  g6e.xlarge->g6e.xlarge   4096     128      431.88        153.67    278.21   2.81                  recompute
56   70B  g6e.xlarge->g6e.xlarge   8192     256      865.21        314.73    550.48   2.75                  recompute
57   70B  g6e.xlarge->g6e.xlarge  16384     512    1,727.84        694.59  1,033.25   2.49                  recompute
58   70B  g6e.xlarge->g6e.xlarge  32768    1024    3,461.39      2,203.47  1,257.92   1.57                  recompute
59   70B  g6e.xlarge->g6e.xlarge  65536    2048    6,920.92      7,590.16   -669.24   0.91                  migration
60    8B    g6.xlarge->g6.xlarge    128      16       52.16         78.70    -26.54   0.66                  migration
61    8B    g6.xlarge->g6.xlarge    256      32      107.76         78.80     28.96   1.37                  recompute
62    8B    g6.xlarge->g6.xlarge    512      64      215.69         94.90    120.79   2.27                  recompute
63    8B    g6.xlarge->g6.xlarge   1024     128      432.78        151.20    281.58   2.86                  recompute
64    8B    g6.xlarge->g6.xlarge   2048     256      865.86        273.80    592.06   3.16                  recompute
65    8B    g6.xlarge->g6.xlarge   4096     512    1,730.49        910.70    819.79   1.90                  recompute
66    8B    g6.xlarge->g6.xlarge   8192    1024    3,460.92      2,195.90  1,265.02   1.58                  recompute
67    8B    g6.xlarge->g6.xlarge  16384    2048    6,920.61      5,050.40  1,870.21   1.37                  recompute
68    8B    g6.xlarge->g6.xlarge  32768    4096   13,856.79           NaN       NaN    NaN  migration (recompute OOM)
69    8B    g6.xlarge->g6.xlarge  65536    8192   27,695.37           NaN       NaN    NaN  migration (recompute OOM)
70    8B   g6.xlarge->g6e.xlarge    128      16       52.73         32.86     19.87   1.60                  recompute
71    8B   g6.xlarge->g6e.xlarge    256      32      108.14         33.40     74.74   3.24                  recompute
72    8B   g6.xlarge->g6e.xlarge    512      64      215.63         36.74    178.89   5.87                  recompute
73    8B   g6.xlarge->g6e.xlarge   1024     128      432.22         48.41    383.81   8.93                  recompute
74    8B   g6.xlarge->g6e.xlarge   2048     256      865.25         84.04    781.21  10.30                  recompute
75    8B   g6.xlarge->g6e.xlarge   4096     512    1,730.49        162.09  1,568.40  10.68                  recompute
76    8B   g6.xlarge->g6e.xlarge   8192    1024    3,461.00        355.33  3,105.67   9.74                  recompute
77    8B   g6.xlarge->g6e.xlarge  16384    2048    6,923.04        989.06  5,933.98   7.00                  recompute
78    8B   g6.xlarge->g6e.xlarge  32768    4096   13,857.03      3,758.70 10,098.33   3.69                  recompute
79    8B   g6.xlarge->g6e.xlarge  65536    8192   27,696.64     10,593.91 17,102.73   2.61                  recompute
80    8B   g6e.xlarge->g6.xlarge    128      16       52.69         78.70    -26.01   0.67                  migration
81    8B   g6e.xlarge->g6.xlarge    256      32      107.60         78.80     28.80   1.37                  recompute
82    8B   g6e.xlarge->g6.xlarge    512      64      215.62         94.90    120.72   2.27                  recompute
83    8B   g6e.xlarge->g6.xlarge   1024     128      431.96        151.20    280.76   2.86                  recompute
84    8B   g6e.xlarge->g6.xlarge   2048     256      865.72        273.80    591.92   3.16                  recompute
85    8B   g6e.xlarge->g6.xlarge   4096     512    1,730.70        910.70    820.00   1.90                  recompute
86    8B   g6e.xlarge->g6.xlarge   8192    1024    3,461.83      2,195.90  1,265.93   1.58                  recompute
87    8B   g6e.xlarge->g6.xlarge  16384    2048    6,918.72      5,050.40  1,868.32   1.37                  recompute
88    8B   g6e.xlarge->g6.xlarge  32768    4096   13,861.02           NaN       NaN    NaN  migration (recompute OOM)
89    8B   g6e.xlarge->g6.xlarge  65536    8192   27,695.86           NaN       NaN    NaN  migration (recompute OOM)
90    8B  g6e.xlarge->g6e.xlarge    128      16       53.46         32.86     20.60   1.63                  recompute
91    8B  g6e.xlarge->g6e.xlarge    256      32      109.31         33.40     75.91   3.27                  recompute
92    8B  g6e.xlarge->g6e.xlarge    512      64      215.73         36.74    178.99   5.87                  recompute
93    8B  g6e.xlarge->g6e.xlarge   1024     128      430.35         48.41    381.94   8.89                  recompute
94    8B  g6e.xlarge->g6e.xlarge   2048     256      865.61         84.04    781.57  10.30                  recompute
95    8B  g6e.xlarge->g6e.xlarge   4096     512    1,730.50        162.09  1,568.41  10.68                  recompute
96    8B  g6e.xlarge->g6e.xlarge   8192    1024    3,460.97        355.33  3,105.64   9.74                  recompute
97    8B  g6e.xlarge->g6e.xlarge  16384    2048    6,923.32        989.06  5,934.26   7.00                  recompute
98    8B  g6e.xlarge->g6e.xlarge  32768    4096   13,849.94      3,758.70 10,091.24   3.68                  recompute
99    8B  g6e.xlarge->g6e.xlarge  65536    8192   27,694.18     10,593.91 17,100.27   2.61                  recompute

## 2. config 별 요약
각 (model, pair) 에서 migration 이 이긴 횟수, ratio 통계, migration 최선/최악 지점.

In [3]:
rows = []
for (m, p), g in df.groupby(['model', 'pair']):
    gv = g.dropna(subset=['recompute_ms'])
    n_oom = int(g['recompute_ms'].isna().sum())
    mig_wins = int((gv['migrate_ms'] < gv['recompute_ms']).sum())
    best = gv.loc[gv['ratio'].idxmin()] if len(gv) else None      # migration 에 가장 유리
    worst = gv.loc[gv['ratio'].idxmax()] if len(gv) else None     # migration 에 가장 불리
    rows.append({
        'model': m, 'pair': p,
        'n_ctx': len(g), 'mig_wins': mig_wins, 'recomp_wins': len(gv) - mig_wins,
        'oom(=mig only)': n_oom,
        'ratio_min': gv['ratio'].min(), 'ratio_median': gv['ratio'].median(), 'ratio_max': gv['ratio'].max(),
        'best_ctx(min ratio)': int(best['ctx']) if best is not None else None,
        'worst_ctx(max ratio)': int(worst['ctx']) if worst is not None else None,
    })
summary = pd.DataFrame(rows)
display(summary)

  model                    pair  n_ctx  mig_wins  recomp_wins  oom(=mig only)  ratio_min  ratio_median  ratio_max  best_ctx(min ratio)  worst_ctx(max ratio)
0    3B    g6.xlarge->g6.xlarge     10         0           10               0       1.19          3.37       6.22                  128                  2048
1    3B   g6.xlarge->g6e.xlarge     10         0           10               0       2.27         11.71      18.05                  128                  4096
2    3B   g6e.xlarge->g6.xlarge     10         0           10               0       1.19          3.36       6.22                  128                  2048
3    3B  g6e.xlarge->g6e.xlarge     10         0           10               0       2.43         11.65      18.06                  128                  4096
4   70B    g6.xlarge->g6.xlarge     10         9            0               1       0.02          0.61       0.76                  128                  8192
5   70B  g6e.xlarge->g6e.xlarge     10         3            7               0       0.29          1.97       2.81                  128                  4096
6    8B    g6.xlarge->g6.xlarge     10         1            7               2       0.66          1.74       3.16                  128                  2048
7    8B   g6.xlarge->g6e.xlarge     10         0           10               0       1.60          6.43      10.68                  128                  4096
8    8B   g6e.xlarge->g6.xlarge     10         1            7               2       0.67          1.74       3.16                  128                  2048
9    8B  g6e.xlarge->g6e.xlarge     10         0           10               0       1.63          6.44      10.68                  128                  4096

## 3. Crossover 분석
context 가 커질수록 recompute 는 superlinear, migration 은 linear 라 승자가 바뀐다.
각 config 에서 `migrate_ms - recompute_ms` 의 부호가 바뀌는 구간을 찾고, log-log 보간으로 crossover context 를 추정한다.

In [4]:
def crossovers(g):
    """부호 변화 구간 + log-log 보간 crossover ctx 추정"""
    g = g.dropna(subset=['recompute_ms']).sort_values('ctx')
    recs = g.to_dict('records')
    out = []
    for a, b in zip(recs, recs[1:]):
        da, db = a['diff_ms'], b['diff_ms']
        if (da < 0) != (db < 0):  # 승자 바뀜
            # log(ratio) 가 log(ctx) 에 선형이라 가정, ratio=1 (log=0) 지점
            la, lb = np.log(a['ratio']), np.log(b['ratio'])
            lca, lcb = np.log(a['ctx']), np.log(b['ctx'])
            lc = lca + (0 - la) * (lcb - lca) / (lb - la)
            out.append({
                'from_ctx': a['ctx'], 'to_ctx': b['ctx'],
                'from_winner': a['faster'], 'to_winner': b['faster'],
                'crossover_ctx~': round(float(np.exp(lc))),
            })
    return out

cross_rows = []
for (m, p), g in df.groupby(['model', 'pair']):
    cs = crossovers(g)
    if not cs:
        gv = g.dropna(subset=['recompute_ms'])
        always = gv['faster'].iloc[0] if len(gv) else 'n/a'
        cross_rows.append({'model': m, 'pair': p, 'note': f'crossover 없음 (항상 {always} 우세)',
                           'from_ctx': None, 'to_ctx': None, 'crossover_ctx~': None})
    else:
        for c in cs:
            cross_rows.append({'model': m, 'pair': p,
                               'note': f"{c['from_winner']} -> {c['to_winner']}",
                               'from_ctx': c['from_ctx'], 'to_ctx': c['to_ctx'],
                               'crossover_ctx~': c['crossover_ctx~']})
display(pd.DataFrame(cross_rows))

   model                    pair                            note  from_ctx    to_ctx  crossover_ctx~
0     3B    g6.xlarge->g6.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN
1     3B   g6.xlarge->g6e.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN
2     3B   g6e.xlarge->g6.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN
3     3B  g6e.xlarge->g6e.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN
4    70B    g6.xlarge->g6.xlarge  crossover 없음 (항상 migration 우세)       NaN       NaN             NaN
5    70B  g6e.xlarge->g6e.xlarge          migration -> recompute    256.00    512.00          332.00
6    70B  g6e.xlarge->g6e.xlarge          recompute -> migration 32,768.00 65,536.00       58,264.00
7     8B    g6.xlarge->g6.xlarge          migration -> recompute    128.00    256.00          190.00
8     8B   g6.xlarge->g6e.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN
9     8B   g6e.xlarge->g6.xlarge          migration -> recompute    128.00    256.00          189.00
10    8B  g6e.xlarge->g6e.xlarge  crossover 없음 (항상 recompute 우세)       NaN       NaN             NaN

## 4. Recompute 불가(OOM) → migration 필수 케이스
destination instance 에서 그 context 를 recompute 할 수 없는 경우. 시간과 무관하게 migration 이 유일한 옵션.

In [5]:
oom = df[df['recompute_ms'].isna()][['model', 'pair', 'ctx', 'kv_MiB', 'migrate_ms']]
print(f'OOM(=migration 필수) 케이스: {len(oom)}건')
display(oom)

OOM(=migration 필수) 케이스: 5건

   model                   pair    ctx  kv_MiB  migrate_ms
49   70B   g6.xlarge->g6.xlarge  65536     512    1,730.47
68    8B   g6.xlarge->g6.xlarge  32768    4096   13,856.79
69    8B   g6.xlarge->g6.xlarge  65536    8192   27,695.37
88    8B  g6e.xlarge->g6.xlarge  32768    4096   13,861.02
89    8B  g6e.xlarge->g6.xlarge  65536    8192   27,695.86

## 5. Break-even 네트워크 대역폭
현재 측정 대역폭은 거의 균일하게 ~0.29 GB/s. 각 지점에서 **migration 이 recompute 와 같아지려면 필요한 대역폭** `= KV_GB / recompute_s`.
이 값이 실제 대역폭보다 크면(=`required/actual = ratio > 1`) 그만큼 네트워크가 빨라져야 migration 이 유리해진다.

In [6]:
be = df.dropna(subset=['recompute_ms']).copy()
be['required/actual(x)'] = be['breakeven_bw_GBps'] / be['bw']
view_be = be[['model', 'pair', 'ctx', 'kv_GB', 'recompute_ms',
              'bw', 'breakeven_bw_GBps', 'required/actual(x)']]
with pd.option_context('display.max_rows', None):
    display(view_be)
print(f"실제 대역폭 평균: {df['bw'].mean():.3f} GB/s")
print(f"migration 이 유리해지려면 필요한 대역폭 중앙값: {be['breakeven_bw_GBps'].median():.2f} GB/s "
      f"(실제 대비 약 {be['required/actual(x)'].median():.1f}x)")

   model                    pair    ctx  kv_GB  recompute_ms   bw  breakeven_bw_GBps  required/actual(x)
0     3B    g6.xlarge->g6.xlarge    128   0.01         37.80 0.30               0.36                1.21
1     3B    g6.xlarge->g6.xlarge    256   0.03         38.00 0.29               0.72                2.48
2     3B    g6.xlarge->g6.xlarge    512   0.05         45.90 0.29               1.19                4.11
3     3B    g6.xlarge->g6.xlarge   1024   0.11         70.00 0.29               1.56                5.39
4     3B    g6.xlarge->g6.xlarge   2048   0.22        121.70 0.29               1.80                6.20
5     3B    g6.xlarge->g6.xlarge   4096   0.44        253.20 0.29               1.73                5.96
6     3B    g6.xlarge->g6.xlarge   8192   0.88        574.60 0.29               1.52                5.25
7     3B    g6.xlarge->g6.xlarge  16384   1.75      2,312.20 0.29               0.76                2.61
8     3B    g6.xlarge->g6.xlarge  32768   3.50      6,382.20 0.29               0.55                1.89
9     3B    g6.xlarge->g6.xlarge  65536   7.00     20,002.80 0.29               0.35                1.21
10    3B   g6.xlarge->g6e.xlarge    128   0.01         20.40 0.29               0.67                2.31
11    3B   g6.xlarge->g6e.xlarge    256   0.03         19.43 0.29               1.41                4.85
12    3B   g6.xlarge->g6e.xlarge    512   0.05         21.02 0.29               2.60                8.97
13    3B   g6.xlarge->g6e.xlarge   1024   0.11         25.83 0.29               4.23               14.60
14    3B   g6.xlarge->g6e.xlarge   2048   0.22         42.64 0.29               5.13               17.69
15    3B   g6.xlarge->g6e.xlarge   4096   0.44         83.88 0.29               5.22               17.99
16    3B   g6.xlarge->g6e.xlarge   8192   0.88        167.93 0.29               5.21               17.97
17    3B   g6.xlarge->g6e.xlarge  16384   1.75        420.83 0.29               4.16               14.34
18    3B   g6.xlarge->g6e.xlarge  32768   3.50      1,381.27 0.29               2.53                8.74
19    3B   g6.xlarge->g6e.xlarge  65536   7.00      5,867.33 0.29               1.19                4.11
20    3B   g6e.xlarge->g6.xlarge    128   0.01         37.80 0.30               0.36                1.21
21    3B   g6e.xlarge->g6.xlarge    256   0.03         38.00 0.29               0.72                2.48
22    3B   g6e.xlarge->g6.xlarge    512   0.05         45.90 0.29               1.19                4.11
23    3B   g6e.xlarge->g6.xlarge   1024   0.11         70.00 0.29               1.56                5.39
24    3B   g6e.xlarge->g6.xlarge   2048   0.22        121.70 0.29               1.80                6.20
25    3B   g6e.xlarge->g6.xlarge   4096   0.44        253.20 0.29               1.73                5.96
26    3B   g6e.xlarge->g6.xlarge   8192   0.88        574.60 0.29               1.52                5.25
27    3B   g6e.xlarge->g6.xlarge  16384   1.75      2,312.20 0.29               0.76                2.61
28    3B   g6e.xlarge->g6.xlarge  32768   3.50      6,382.20 0.29               0.55                1.89
29    3B   g6e.xlarge->g6.xlarge  65536   7.00     20,002.80 0.29               0.35                1.21
30    3B  g6e.xlarge->g6e.xlarge    128   0.01         20.40 0.28               0.67                2.39
31    3B  g6e.xlarge->g6e.xlarge    256   0.03         19.43 0.29               1.41                4.85
32    3B  g6e.xlarge->g6e.xlarge    512   0.05         21.02 0.29               2.60                8.97
33    3B  g6e.xlarge->g6e.xlarge   1024   0.11         25.83 0.29               4.23               14.60
34    3B  g6e.xlarge->g6e.xlarge   2048   0.22         42.64 0.29               5.13               17.69
35    3B  g6e.xlarge->g6e.xlarge   4096   0.44         83.88 0.29               5.22               17.99
36    3B  g6e.xlarge->g6e.xlarge   8192   0.88        167.93 0.29               5.21               17.97
37    3B  g6e.xlarge->g6e.xlarge  16384   1.75        420.83 0.29               4.16               14.34
38    3B  g6e.xlarge->g6e.xlarge  32768   3.50      1,381.27 0.29               2.53                8.74
39    3B  g6e.xlarge->g6e.xlarge  65536   7.00      5,867.33 0.29               1.19                4.11
40   70B    g6.xlarge->g6.xlarge    128   0.00         30.60 1.53               0.03                0.02
41   70B    g6.xlarge->g6.xlarge    256   0.00         30.30 0.44               0.06                0.15
42   70B    g6.xlarge->g6.xlarge    512   0.00         33.30 0.35               0.12                0.34
43   70B    g6.xlarge->g6.xlarge   1024   0.01         45.40 0.29               0.17                0.59
44   70B    g6.xlarge->g6.xlarge   2048   0.02         75.50 0.29               0.21                0.71
45   70B    g6.xlarge->g6.xlarge   4096   0.03        143.10 0.29               0.22                0.75
46   70B    g6.xlarge->g6.xlarge   8192   0.06        283.40 0.29               0.22                0.76
47   70B    g6.xlarge->g6.xlarge  16384   0.12        602.00 0.29               0.21                0.72
48   70B    g6.xlarge->g6.xlarge  32768   0.25      1,415.60 0.29               0.18                0.61
50   70B  g6e.xlarge->g6e.xlarge    128   0.00         32.73 0.42               0.12                0.28
51   70B  g6e.xlarge->g6e.xlarge    256   0.01         32.82 0.30               0.24                0.79
52   70B  g6e.xlarge->g6e.xlarge    512   0.02         36.17 0.29               0.43                1.49
53   70B  g6e.xlarge->g6e.xlarge   1024   0.03         45.62 0.29               0.69                2.36
54   70B  g6e.xlarge->g6e.xlarge   2048   0.06         77.68 0.29               0.80                2.77
55   70B  g6e.xlarge->g6e.xlarge   4096   0.12        153.67 0.29               0.81                2.80
56   70B  g6e.xlarge->g6e.xlarge   8192   0.25        314.73 0.29               0.79                2.74
57   70B  g6e.xlarge->g6e.xlarge  16384   0.50        694.59 0.29               0.72                2.48
58   70B  g6e.xlarge->g6e.xlarge  32768   1.00      2,203.47 0.29               0.45                1.56
59   70B  g6e.xlarge->g6e.xlarge  65536   2.00      7,590.16 0.29               0.26                0.91
60    8B    g6.xlarge->g6.xlarge    128   0.02         78.70 0.30               0.20                0.66
61    8B    g6.xlarge->g6.xlarge    256   0.03         78.80 0.29               0.40                1.37
62    8B    g6.xlarge->g6.xlarge    512   0.06         94.90 0.29               0.66                2.27
63    8B    g6.xlarge->g6.xlarge   1024   0.12        151.20 0.29               0.83                2.85
64    8B    g6.xlarge->g6.xlarge   2048   0.25        273.80 0.29               0.91                3.15
65    8B    g6.xlarge->g6.xlarge   4096   0.50        910.70 0.29               0.55                1.89
66    8B    g6.xlarge->g6.xlarge   8192   1.00      2,195.90 0.29               0.46                1.57
67    8B    g6.xlarge->g6.xlarge  16384   2.00      5,050.40 0.29               0.40                1.37
70    8B   g6.xlarge->g6e.xlarge    128   0.02         32.86 0.30               0.48                1.59
71    8B   g6.xlarge->g6e.xlarge    256   0.03         33.40 0.29               0.94                3.23
72    8B   g6.xlarge->g6e.xlarge    512   0.06         36.74 0.29               1.70                5.87
73    8B   g6.xlarge->g6e.xlarge   1024   0.12         48.41 0.29               2.58                8.90
74    8B   g6.xlarge->g6e.xlarge   2048   0.25         84.04 0.29               2.97               10.26
75    8B   g6.xlarge->g6e.xlarge   4096   0.50        162.09 0.29               3.08               10.64
76    8B   g6.xlarge->g6e.xlarge   8192   1.00        355.33 0.29               2.81                9.70
77    8B   g6.xlarge->g6e.xlarge  16384   2.00        989.06 0.29               2.02                6.97
78    8B   g6.xlarge->g6e.xlarge  32768   4.00      3,758.70 0.29               1.06                3.67
79    8B   g6.xlarge->g6e.xlarge  65536   8.00     10,593.91 0.29               0.76                2.60
80    8B   g6e.xlarge->g6.xlarge    128   0.02         78.70 0.30               0.20                0.66
81    8B   g6e.xlarge->g6.xlarge    256   0.03         78.80 0.29               0.40                1.37
82    8B   g6e.xlarge->g6.xlarge    512   0.06         94.90 0.29               0.66                2.27
83    8B   g6e.xlarge->g6.xlarge   1024   0.12        151.20 0.29               0.83                2.85
84    8B   g6e.xlarge->g6.xlarge   2048   0.25        273.80 0.29               0.91                3.15
85    8B   g6e.xlarge->g6.xlarge   4096   0.50        910.70 0.29               0.55                1.89
86    8B   g6e.xlarge->g6.xlarge   8192   1.00      2,195.90 0.29               0.46                1.57
87    8B   g6e.xlarge->g6.xlarge  16384   2.00      5,050.40 0.29               0.40                1.37
90    8B  g6e.xlarge->g6e.xlarge    128   0.02         32.86 0.29               0.48                1.64
91    8B  g6e.xlarge->g6e.xlarge    256   0.03         33.40 0.29               0.94                3.23
92    8B  g6e.xlarge->g6e.xlarge    512   0.06         36.74 0.29               1.70                5.87
93    8B  g6e.xlarge->g6e.xlarge   1024   0.12         48.41 0.29               2.58                8.90
94    8B  g6e.xlarge->g6e.xlarge   2048   0.25         84.04 0.29               2.97               10.26
95    8B  g6e.xlarge->g6e.xlarge   4096   0.50        162.09 0.29               3.08               10.64
96    8B  g6e.xlarge->g6e.xlarge   8192   1.00        355.33 0.29               2.81                9.70
97    8B  g6e.xlarge->g6e.xlarge  16384   2.00        989.06 0.29               2.02                6.97
98    8B  g6e.xlarge->g6e.xlarge  32768   4.00      3,758.70 0.29               1.06                3.67
99    8B  g6e.xlarge->g6e.xlarge  65536   8.00     10,593.91 0.29               0.76                2.60

실제 대역폭 평균: 0.306 GB/s
migration 이 유리해지려면 필요한 대역폭 중앙값: 0.83 GB/s (실제 대비 약 2.9x)

## 6. (참고) 70B per-layer 정규화 view
`plot_comparison.py` 와 동일하게 g6.xlarge=÷2, g6e.xlarge=÷8 로 per-layer 환산. (위 직접 비교의 ratio 는 정규화와 무관하게 동일함을 확인용.)

In [7]:
LAYERS = {'g6.xlarge': 2, 'g6e.xlarge': 8}
g70 = df[df['model'] == '70B'].copy()
g70['nlayer'] = g70['dst'].map(LAYERS)
g70['migrate_ms/layer']   = g70['migrate_ms'] / g70['nlayer']
g70['recompute_ms/layer'] = g70['recompute_ms'] / g70['nlayer']
display(g70[['pair', 'ctx', 'nlayer', 'migrate_ms/layer', 'recompute_ms/layer', 'ratio', 'faster']])

                      pair    ctx  nlayer  migrate_ms/layer  recompute_ms/layer  ratio                     faster
40    g6.xlarge->g6.xlarge    128       2              0.32               15.30   0.02                  migration
41    g6.xlarge->g6.xlarge    256       2              2.22               15.15   0.15                  migration
42    g6.xlarge->g6.xlarge    512       2              5.57               16.65   0.33                  migration
43    g6.xlarge->g6.xlarge   1024       2             13.48               22.70   0.59                  migration
44    g6.xlarge->g6.xlarge   2048       2             27.02               37.75   0.72                  migration
45    g6.xlarge->g6.xlarge   4096       2             53.56               71.55   0.75                  migration
46    g6.xlarge->g6.xlarge   8192       2            108.17              141.70   0.76                  migration
47    g6.xlarge->g6.xlarge  16384       2            216.41              301.00   0.72                  migration
48    g6.xlarge->g6.xlarge  32768       2            431.90              707.80   0.61                  migration
49    g6.xlarge->g6.xlarge  65536       2            865.24                 NaN    NaN  migration (recompute OOM)
50  g6e.xlarge->g6e.xlarge    128       8              1.17                4.09   0.29                  migration
51  g6e.xlarge->g6e.xlarge    256       8              3.22                4.10   0.78                  migration
52  g6e.xlarge->g6e.xlarge    512       8              6.76                4.52   1.50                  recompute
53  g6e.xlarge->g6e.xlarge   1024       8             13.56                5.70   2.38                  recompute
54  g6e.xlarge->g6e.xlarge   2048       8             26.98                9.71   2.78                  recompute
55  g6e.xlarge->g6e.xlarge   4096       8             53.98               19.21   2.81                  recompute
56  g6e.xlarge->g6e.xlarge   8192       8            108.15               39.34   2.75                  recompute
57  g6e.xlarge->g6e.xlarge  16384       8            215.98               86.82   2.49                  recompute
58  g6e.xlarge->g6e.xlarge  32768       8            432.67              275.43   1.57                  recompute
59  g6e.xlarge->g6e.xlarge  65536       8            865.12              948.77   0.91                  migration

## 7. 종합 요약 (수치)

In [8]:
gv = df.dropna(subset=['recompute_ms'])
print('=== 전체 ===')
print(f"비교 가능한 지점: {len(gv)}, 그 중 migration 이 더 빠른 경우: {(gv['migrate_ms']<gv['recompute_ms']).sum()} "
      f"({(gv['migrate_ms']<gv['recompute_ms']).mean()*100:.0f}%)")
print(f"OOM 으로 migration 필수: {df['recompute_ms'].isna().sum()} 건")
print(f"ratio(=migrate/recompute) 중앙값: {gv['ratio'].median():.2f}  (>1 = recompute 우세)")
print()
print('=== model 별 ratio 중앙값 ===')
print(gv.groupby('model')['ratio'].median().round(2).to_string())
print()
print('=== destination instance 별 ratio 중앙값 ===')
print(gv.groupby('dst')['ratio'].median().round(2).to_string())
print()
print('=== migration 이 이긴 지점들 ===')
win = gv[gv['migrate_ms'] < gv['recompute_ms']][['model', 'pair', 'ctx', 'migrate_ms', 'recompute_ms', 'ratio']]
print(win.to_string(index=False) if len(win) else '  (없음)')

=== 전체 ===
비교 가능한 지점: 95, 그 중 migration 이 더 빠른 경우: 14 (15%)
OOM 으로 migration 필수: 5 건
ratio(=migrate/recompute) 중앙값: 2.86  (>1 = recompute 우세)

=== model 별 ratio 중앙값 ===
model
3B    5.32
70B   0.76
8B    3.01

=== destination instance 별 ratio 중앙값 ===
dst
g6.xlarge    1.90
g6e.xlarge   5.87

=== migration 이 이긴 지점들 ===
model                   pair   ctx  migrate_ms  recompute_ms  ratio
  70B   g6.xlarge->g6.xlarge   128        0.64         30.60   0.02
  70B   g6.xlarge->g6.xlarge   256        4.44         30.30   0.15
  70B   g6.xlarge->g6.xlarge   512       11.14         33.30   0.33
  70B   g6.xlarge->g6.xlarge  1024       26.96         45.40   0.59
  70B   g6.xlarge->g6.xlarge  2048       54.04         75.50   0.72
  70B   g6.xlarge->g6.xlarge  4096      107.12        143.10   0.75
  70B   g6.xlarge->g6.xlarge  8192      216.35        283.40   0.76
  70B   g6.xlarge->g6.xlarge 16384      432.82        602.00   0.72
  70B   g6.xlarge->g6.xlarge 32768      863.81      1,415.60   0.61
  70B g6e.xlarge->g6e.xlarge   128        9.33         32.73   0.29
  70B g6e.xlarge->g6e.xlarge   256       25.75         32.82   0.78
  70B g6e.xlarge->g6e.xlarge 65536    6,920.92      7,590.16   0.91
   8B   g6.xlarge->g6.xlarge   128       52.16         78.70   0.66
   8B  g6e.xlarge->g6.xlarge   128       52.69         78.70   0.67